AllCops:
  # RunRailsCops: true
  Exclude:
    - 'bin/*'

Style/SignalException:
  EnforcedStyle: only_raise

Style/Documentation:
  Enabled: false

LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20
